//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeingChart
    {
        public int ID { get; set; }
        public string Path { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
