//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppTable
    {
        public int ID { get; set; }
        public string Website { get; set; }
        public string Name { get; set; }
        public string ContactEmail { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
