//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierSentOrder
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime SentDate { get; set; }
        public System.DateTime EstimatedReceiveDate { get; set; }
    }
}
