//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaza.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteCredential
    {
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
