//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zaza.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZazaEntities : DbContext
    {
        public ZazaEntities()
            : base("name=ZazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<ProductMedia> ProductMedias { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<SizeingChart> SizeingCharts { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<SupplierSentOrder> SupplierSentOrders { get; set; }
        public DbSet<SuppTable> SuppTables { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WhishList> WhishLists { get; set; }
    }
}
